update keydb 6.3.3 -> 6.3.4
elisasre/charts pull request #24
Opened 2023-10-31 11:39 UTC by kraashen

2023-10-31 15:53 UTC, rofafor requested changes

2023-10-31 15:53 UTC, rofafor commented on keydb/Dockerfile
> +FROM docker.io/eqalpha/keydb:alpine_x86_64_v6.3.4
tämä on nyt väärin - omaa imagea ei pitäisi enää tarvita

2023-11-01 06:25 UTC, kraashen commented on keydb/Dockerfile
> +FROM docker.io/eqalpha/keydb:alpine_x86_64_v6.3.4
Ymmärsinkö okein, eli viitattaisiin vain jatkossa suoraan chartin valueseissa upstreamin imageen?

2023-11-01 08:37 UTC, zetaab commented on keydb/Dockerfile
> +FROM docker.io/eqalpha/keydb:alpine_x86_64_v6.3.4
jep, eli ei pitäs enää tarvita sitä omaa custom imagea, jolloin me voidaan käyttää suoraan upstreamista tulevaa imagea. Toisinsanoen: dockerfile on turha ja charttiin pitäs laittaa toinen image defaultiksi

2023-11-01 09:48 UTC, zetaab commented on .github/workflows/release.yml
>          push: true
omat imaget ei täälkään ole enää tarpeen

nää myös https://github.com/elisasre/charts/blob/master/keydb/values.yaml#L4-L5 pitäs päivittää

2023-11-01 09:55 UTC, zetaab commented on .github/workflows/release.yml
>          push: true
@kraashen ^

2023-11-01 10:05 UTC, kraashen commented on .github/workflows/release.yml
>          push: true
Kas, nämä näemmä jäi commitista. Lisäsin fixuppina edelliseen committiin.

2023-11-01 10:15 UTC, zetaab approved these changes

2023-11-01 11:37 UTC, rofafor approved these changes

2023-11-01 11:49 UTC, merged